name: Deploy Node.js app to Azure Web App - Test-stage-melle

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Zip the build directory for deployment
        run: zip -r build.zip ./lob-dev-app/build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "Test-stage-melle"
          slot-name: "Production"
          package: build.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4F2749EF536D46F898274969170B8238 }}
