name: Build and deploy Node.js app to Azure Web App - Test-stage-melle

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: npm install and build
        run: |
          npm install
          npm run build
        working-directory: ./lob-dev-app # Make sure this directory contains your React app

      - name: List contents of the build directory
        run: ls -l lob-dev-app/build # This will confirm if the build directory has the build artifacts

      - name: Zip artifact for deployment
        run: zip -r release.zip lob-dev-app/build/* # This zips the contents of the build directory

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip # This is the path to the zip file you just created

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "Test-stage-melle"
          slot-name: "Production"
          package: release.zip # This should point to the zip file, not a directory
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4F2749EF536D46F898274969170B8238 }}
