name: Build and deploy Node.js app to Azure Web App - Test-stage-melle

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install npm dependencies
        run: npm install
        working-directory: ./lob-dev-app

      - name: Build React app
        run: npm run build
        working-directory: ./lob-dev-app

      - name: Zip the build artifacts
        run: zip -r build.zip ./build
        working-directory: ./lob-dev-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "Test-stage-melle"
          slot-name: "Production"
          package: ./lob-dev-app/build.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4F2749EF536D46F898274969170B8238 }}
